GeneratePassword/GeneratePassword/Models/CipherModel/CipherViewModel.cs
namespace GeneratePassword.Models.CipherModel
{
    public class CipherViewModel
    {
        public string? Description { get; set; }
        public string? Password { get; set; }
    }
}

GeneratePassword/GeneratePassword/Models/ErrorViewModel.cs
namespace GeneratePassword.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GeneratePassword/GeneratePassword/Controllers/DefaultController.cs
using GeneratePassword.DataAccessLayer.Concrete;
using GeneratePassword.EntityLayer.Concrete;
using GeneratePassword.Messages;
using GeneratePassword.Models.CipherModel;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using X.PagedList;

namespace GeneratePassword.Controllers
{
	public class DefaultController : Controller
	{
		private readonly Context _context;
		private readonly IToastNotification _toast;

		NtoastnotifyMessage ntoastnotifyMessage = new NtoastnotifyMessage();
		Random random = new Random();

		public DefaultController(Context context, IToastNotification toast)
		{
			_context = context;
			_toast = toast;
		}


		[HttpGet]
		public IActionResult Index()
		{
			//int length = 5;
			//string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789#$%^&!@-*()_+";

			//string password = new string(Enumerable.Repeat(chars, length).Select(s => s[random.Next(s.Length)]).ToArray());

			//ViewBag.Random = password;

			var code = random.Next(100000, 1000000);
			ViewBag.Code = "Kydb_V@ri" + code + "!" + DateTime.Now.Year;
			return View();
		}
		[HttpPost]
		public IActionResult Index(CipherViewModel model)
		{
			var code = random.Next(100000, 1000000);
			ViewBag.Code = "Kydb_V@ri" + code + "!" + DateTime.Now.Year;

			if (ModelState.IsValid)
			{
				if (ViewBag.Code != model.Password)
				{
					var values = new Cipher();
					values.GuidID = new Guid();
					values.Password = model.Password;
					values.Description = model.Description;

					_context.Ciphers.Add(values);
					_context.SaveChanges();

					_toast.AddSuccessToastMessage(ntoastnotifyMessage.descriptionSuccess,
						new ToastrOptions { Title = ntoastnotifyMessage.descriptionSuccessTitle });

					return RedirectToAction("CipherList");
				}
				else
				{
					_toast.AddErrorToastMessage(ntoastnotifyMessage.descriptionError,
						new ToastrOptions { Title = ntoastnotifyMessage.descriptionErrorTitle });

					return View("Index");
				}

			}

			return View();
		}
		public IActionResult CipherList(string p, int page = 1)
		{
			var values = from x in _context.Ciphers select x;

			if (!string.IsNullOrEmpty(p))
			{
				values = values.Where(c => c.Description.Contains(p));
			}

			return View(values.OrderByDescending(i => i.GuidID).ToPagedList(page, 5));
		}

	}
}

GeneratePassword/GeneratePassword/Controllers/HomeController.cs
using GeneratePassword.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GeneratePassword.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GeneratePassword/GeneratePassword/Views/Default/CipherList.cshtml
@using GeneratePassword.EntityLayer.Concrete
@using X.PagedList.Mvc.Core
@using X.PagedList
@model IPagedList<GeneratePassword.EntityLayer.Concrete.Cipher>


@{
	ViewData["Title"] = "Şifre Listesi";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
	int number = 0;
}

<div class="card mt-5">
	<div class="card-header">
		<h4>Şifre Listesi</h4>
	</div>
	<div class="card-body">

		@using (Html.BeginForm("CipherList", "Default", FormMethod.Post))
		{
			<div class="mt-3">
				@Html.TextBox("p")
				<input value="Ara" type="submit" class="btn btn-warning" />
			</div>
		}

		<table class="table mt-3">
			@if (Model.Count == 0)
			{
				<thead>
					<tr>
						<th scope="col">#</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th>Tabloda herhangi bir veri bulunmamaktadır.</th>
					</tr>
				</tbody>
			}
			else
			{
				<thead>
					<tr>
						<th>#</th>
						<th>Tarih ve Sayı</th>
						<th>Şifre</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						@*number++;*@
						<tr>
							@*<th scope="row">@number</th>*@
							<th></th>
							<td>@item.Description</td>
							<td>
								@item.Password
								@*<input type="password" value="@item.Password" class="GuidID">*@
								@*<input type="checkbox" onclick="myFunction()">Şifreyi Göster*@

							</td>
						</tr>
					}

				</tbody>
			}

		</table>

	</div>

	<div class="card-footer mt-3">
		<span>
			@Html.PagedListPager((IPagedList)Model, page =>Url.Action("CipherList", new {page}), new X.PagedList.Web.Common.PagedListRenderOptions
			{
			LiElementClasses = new List<string>{"page-link"}

			})
		</span>
		<a href="/Default/Index/" class="btn btn-success">
			<i class="fa fa-solid fa-rotate-right"></i>
			Şifre Ekranına Git
		</a>
	</div>
</div>

GeneratePassword/GeneratePassword/Views/Default/Index.cshtml
@model CipherViewModel
@{
	ViewData["Title"] = "Şifre Oluşturma Ekranı";
	Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card mt-5">
	<div class="card-header">
		<h4>Şifre Oluşturma Ekranı</h4>
		@*<h4>@ViewBag.Random</h4>*@
	</div>
	<div class="card-body">
		<div class="container mt-3">
			<div class="justify-content-md-around">
				<form method="post" asp-action="Index" asp-controller="Default">

					<input type="text" asp-for="Password" value="@ViewBag.Code" class="form-control" readonly />
					<input type="text" asp-for="Description" class="form-control mt-3" placeholder="Tarih ve Sayı Girin" required />

					<button type="submit" class="btn btn-warning mt-3">Kaydet</button>

				</form>
			</div>
		</div>
	</div>
	<div class="card-footer mt-3">
		<a href="/Default/CipherList/" class="btn btn-danger">
			<i class="fa fa-solid fa-rotate-right"></i>
			Şifre Listesine Git
		</a>
	</div>
</div>

GeneratePassword/GeneratePassword/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GeneratePassword/GeneratePassword/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GeneratePassword.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />

</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @await Component.InvokeAsync("NToastNotify")

</body>
</html>